'use strict';

const { STATUS_NAMES } = require('./status');

function getObjectDefinitions() {
  return [
    {
      id: 'info',
      type: 'channel',
      common: {
        name: 'Information',
      },
      native: {},
    },
    {
      id: 'info.connection',
      type: 'state',
      common: {
        name: 'Connection to charger or cloud',
        type: 'boolean',
        role: 'indicator.connected',
        read: true,
        write: false,
        def: false,
      },
      native: {},
    },
    {
      id: 'info.transportConfigured',
      type: 'state',
      common: {
        name: 'Configured transport',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'info.transportActive',
      type: 'state',
      common: {
        name: 'Active transport',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'info.lastError',
      type: 'state',
      common: {
        name: 'Last error',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'info.lastPoll',
      type: 'state',
      common: {
        name: 'Last successful poll',
        type: 'number',
        role: 'date',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger',
      type: 'device',
      common: {
        name: 'Duosida charger',
      },
      native: {},
    },
    {
      id: 'charger.info',
      type: 'channel',
      common: {
        name: 'Charger information',
      },
      native: {},
    },
    {
      id: 'charger.info.host',
      type: 'state',
      common: {
        name: 'Resolved host / endpoint',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.info.deviceId',
      type: 'state',
      common: {
        name: 'Device ID',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.info.name',
      type: 'state',
      common: {
        name: 'Charger name',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.info.model',
      type: 'state',
      common: {
        name: 'Model',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.info.manufacturer',
      type: 'state',
      common: {
        name: 'Manufacturer',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.info.firmware',
      type: 'state',
      common: {
        name: 'Firmware',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.info.serialNumber',
      type: 'state',
      common: {
        name: 'Serial number',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status',
      type: 'channel',
      common: {
        name: 'Charger status',
      },
      native: {},
    },
    {
      id: 'charger.status.online',
      type: 'state',
      common: {
        name: 'Device reachable / online',
        type: 'boolean',
        role: 'indicator.reachable',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.stateCode',
      type: 'state',
      common: {
        name: 'State code',
        type: 'number',
        role: 'value',
        read: true,
        write: false,
        states: STATUS_NAMES,
      },
      native: {},
    },
    {
      id: 'charger.status.state',
      type: 'state',
      common: {
        name: 'State',
        type: 'string',
        role: 'text',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.isCharging',
      type: 'state',
      common: {
        name: 'Charging active',
        type: 'boolean',
        role: 'sensor.switch',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.error',
      type: 'state',
      common: {
        name: 'Error present',
        type: 'boolean',
        role: 'indicator.error',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.errorCode',
      type: 'state',
      common: {
        name: 'Error code',
        type: 'number',
        role: 'value',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.voltage',
      type: 'state',
      common: {
        name: 'Voltage L1',
        type: 'number',
        role: 'value.voltage',
        unit: 'V',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.voltageL2',
      type: 'state',
      common: {
        name: 'Voltage L2',
        type: 'number',
        role: 'value.voltage',
        unit: 'V',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.voltageL3',
      type: 'state',
      common: {
        name: 'Voltage L3',
        type: 'number',
        role: 'value.voltage',
        unit: 'V',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.current',
      type: 'state',
      common: {
        name: 'Current L1',
        type: 'number',
        role: 'value.current',
        unit: 'A',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.currentL2',
      type: 'state',
      common: {
        name: 'Current L2',
        type: 'number',
        role: 'value.current',
        unit: 'A',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.currentL3',
      type: 'state',
      common: {
        name: 'Current L3',
        type: 'number',
        role: 'value.current',
        unit: 'A',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.power',
      type: 'state',
      common: {
        name: 'Power',
        type: 'number',
        role: 'value.power',
        unit: 'W',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.temperature',
      type: 'state',
      common: {
        name: 'Station temperature',
        type: 'number',
        role: 'value.temperature',
        unit: '°C',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.temperatureInternal',
      type: 'state',
      common: {
        name: 'Internal temperature',
        type: 'number',
        role: 'value.temperature',
        unit: '°C',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.cpVoltage',
      type: 'state',
      common: {
        name: 'CP voltage',
        type: 'number',
        role: 'value.voltage',
        unit: 'V',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.sessionEnergy',
      type: 'state',
      common: {
        name: 'Session energy',
        type: 'number',
        role: 'value.energy',
        unit: 'kWh',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.sessionStart',
      type: 'state',
      common: {
        name: 'Session start',
        type: 'number',
        role: 'date',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.sessionDurationMin',
      type: 'state',
      common: {
        name: 'Session duration',
        type: 'number',
        role: 'value',
        unit: 'min',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.energyToday',
      type: 'state',
      common: {
        name: 'Energy today',
        type: 'number',
        role: 'value.energy',
        unit: 'kWh',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.energyTotal',
      type: 'state',
      common: {
        name: 'Energy total',
        type: 'number',
        role: 'value.energy',
        unit: 'kWh',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.accEnergy',
      type: 'state',
      common: {
        name: 'Accumulated energy',
        type: 'number',
        role: 'value.energy',
        unit: 'kWh',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.accEnergy2',
      type: 'state',
      common: {
        name: 'Accumulated energy 2',
        type: 'number',
        role: 'value.energy',
        unit: 'kWh',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.status.maxCurrentReported',
      type: 'state',
      common: {
        name: 'Reported max current',
        type: 'number',
        role: 'value.current',
        unit: 'A',
        read: true,
        write: false,
      },
      native: {},
    },
    {
      id: 'charger.control',
      type: 'channel',
      common: {
        name: 'Charger control',
      },
      native: {},
    },
    {
      id: 'charger.control.refresh',
      type: 'state',
      common: {
        name: 'Refresh now',
        type: 'boolean',
        role: 'button',
        read: false,
        write: true,
      },
      native: {},
    },
    {
      id: 'charger.control.start',
      type: 'state',
      common: {
        name: 'Start charging',
        type: 'boolean',
        role: 'button.start',
        read: false,
        write: true,
      },
      native: {},
    },
    {
      id: 'charger.control.stop',
      type: 'state',
      common: {
        name: 'Stop charging',
        type: 'boolean',
        role: 'button.stop',
        read: false,
        write: true,
      },
      native: {},
    },
    {
      id: 'charger.control.maxCurrent',
      type: 'state',
      common: {
        name: 'Target max current',
        type: 'number',
        role: 'level.current',
        unit: 'A',
        min: 6,
        max: 32,
        step: 1,
        read: true,
        write: true,
      },
      native: {},
    },
    {
      id: 'charger.control.directWorkMode',
      type: 'state',
      common: {
        name: 'Direct work mode / plug and charge',
        type: 'boolean',
        role: 'switch.setting',
        read: true,
        write: true,
      },
      native: {},
    },
    {
      id: 'charger.control.levelDetection',
      type: 'state',
      common: {
        name: 'Level detection / CP -12V check',
        type: 'boolean',
        role: 'switch.setting',
        read: true,
        write: true,
      },
      native: {},
    },
    {
      id: 'charger.control.stopOnDisconnect',
      type: 'state',
      common: {
        name: 'Stop on EV disconnect',
        type: 'boolean',
        role: 'switch.setting',
        read: true,
        write: true,
      },
      native: {},
    },
    {
      id: 'charger.control.ledBrightness',
      type: 'state',
      common: {
        name: 'LED brightness',
        type: 'number',
        role: 'level.brightness',
        min: 0,
        max: 3,
        step: 1,
        read: true,
        write: true,
      },
      native: {},
    },
  ];
}

module.exports = {
  getObjectDefinitions,
};
